// 为 Vite 生产产物生成零依赖 Service Worker。
// 构建时扫描 dist，把带 hash 的 JS/CSS、图片和应用壳全部预缓存。
import { createHash } from 'node:crypto'
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, relative, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const dist = resolve(root, 'dist')

async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true })
  const files = []
  for (const entry of entries) {
    const path = resolve(dir, entry.name)
    if (entry.isDirectory()) files.push(...await walk(path))
    else files.push(path)
  }
  return files
}

const files = (await walk(dist))
  .filter((file) =>
    !file.endsWith('sw.js') &&
    !file.endsWith('.map') &&
    !file.endsWith('/logo.png') &&
    !file.endsWith('/logo-v2.png'),
  )
  .sort()
const hash = createHash('sha256')
const assets = []

for (const file of files) {
  const url = `/${relative(dist, file).split(sep).join('/')}`
  assets.push(url)
  hash.update(url)
  hash.update(await readFile(file))
}

const version = hash.digest('hex').slice(0, 12)
const source = `// Generated by scripts/build-sw.mjs — do not edit dist/sw.js directly.
const CACHE_NAME = 'math-train-${version}'
const PRECACHE = ${JSON.stringify(assets, null, 2)}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((key) => key.startsWith('math-train-') && key !== CACHE_NAME)
          .map((key) => caches.delete(key)),
      ))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const { request } = event
  if (request.method !== 'GET') return
  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return

  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone()
          caches.open(CACHE_NAME).then((cache) => cache.put('/index.html', copy))
          return response
        })
        .catch(() => caches.match('/index.html').then((cached) => cached || caches.match('/'))),
    )
    return
  }

  event.respondWith(
    caches.match(request).then((cached) => cached || fetch(request).then((response) => {
      if (response.ok) {
        const copy = response.clone()
        caches.open(CACHE_NAME).then((cache) => cache.put(request, copy))
      }
      return response
    })),
  )
})
`

await writeFile(resolve(dist, 'sw.js'), source)
console.log(`✓ 离线资源已生成：${assets.length} 个文件，缓存版本 ${version}`)
